defmodule SWGOHCompanion.SDK.Acronyms do

  @acronyms %{
    "ah" => "Amilyn Holdo",
    "at" => "Ahsoka Tano",
    "av" => "Asajj Ventress",
    "b2" => "B2 Super Battle Droid",
    "bb8" => "BB-8",
    "bs" => "Bastila Shan",
    "bsf" => "Bastila Shan (Fallen)",
    "c3po" => "C-3PO",
    "cc" => "Chief Chirpa",
    "cd" => "Count Dooku",
    "ddk" => "Droideka",
    "dm" => "Darth Maul",
    "dn" => "Darth Nihilus",
    "dr" => "Darth Revan",
    "dv" => "Darth Vader",
    "eb" => "Ezra Bridger",
    "es" => "Ewok Scout",
    "ee" => "Ewok Elder",
    "fotp" => "First Order TIE Pilot",
    "fox" => "First Order Executioner",
    "gas" => "General Skywalker",
    "gba" => "Geonosian Brood Alpha",
    "gg" => "General Grievous",
    "gk" => "General Kenobi",
    "gmy" => "Grand Master Yoda",
    "gso" => "Geonosian Soldier",
    "gsp" => "Geonosian Spy",
    "hk" => "HK-47",
    "hs" => "Hera Syndulla",
    "hux" => "General Hux",
    "jb" => "Jolee Bindo",
    "jtr" => "Rey (Jedi Training)",
    "jka" => "Jedi Knight Anakin",
    "jkr" => "Jedi Knight Revan",
    "kj" => "Kanan Jarrus",
    "kr" => "Kylo Ren",
    "kru" => "Kylo Ren (Unmasked)",
    "l337" => "L3-37",
    "mt" => "Mother Talzin",
    "mw" => "Mace Windu",
    "ng" => "Nute Gunray",
    "ni" => "Nightsister Initiate",
    "nz" => "Nightsister Zombie",
    "od" => "Old Daka",
    "padme" => "Padmé Amidala",
    "ptl" => "Poggle the Lesser",
    "qira" => "Qi'ra",
    "rs" => "Rey (Scavenger)",
    "set" => "Sith Empire Trooper",
    "sf" => "Sun Fac",
    "sion" => "Darth Sion",
    "so" => "Savage Opress",
    "traya" => "Darth Traya",
    "vsc" => "Veteran Smuggler Chewbacca",
    "yhs" => "Young Han Solo",
    "ylc" => "Young Lando Calrissian",
    "zeb" => "Garazeb \"Zeb\" Orrelios"
  }


  def expand_acronyms(characters) do
    characters
    |> Enum.map(&{&1, Map.get(@acronyms, String.downcase(&1), &1)})
  end
end
