defmodule SWGOHCompanion.SDK.Acronyms do

  @acronyms %{
    "ah" => "Amilyn Holdo",
    "arct" => "ARC Trooper",
    "ap" => "Admiral Piett",
    "at" => "Ahsoka Tano",
    "av" => "Asajj Ventress",
    "b2" => "B2 Super Battle Droid",
    "bando" => "The Mandalorian (Beskar Armor)",
    "bb8" => "BB-8",
    "boba" => "Boba Fett",
    "bossk" => "Bossk",
    "bs" => "Bastila Shan",
    "bsf" => "Bastila Shan (Fallen)",
    "c3po" => "C-3PO",
    "candy" => "Canderous Ordo",
    "ca" => "Cassian Andor",
    "cc" => "Chief Chirpa",
    "cd" => "Count Dooku",
    "chewie" => "Chewbacca",
    "chs" => "Captain Han Solo",
    "cls" => "Commander Luke Skywalker",
    "co" => "Carth Onasi",
    "cs" => "Colonel Starck",
    "ctecho" => "CT-21-0408 \"Echo\"",
    "darkt" => "Dark Trooper",
    "ddk" => "Droideka",
    "deatht" => "Death Trooper",
    "dm" => "Darth Maul",
    "dn" => "Darth Nihilus",
    "dr" => "Darth Revan",
    "dv" => "Darth Vader",
    "eb" => "Ezra Bridger",
    "en" => "Enfys Nest",
    "es" => "Ewok Scout",
    "ee" => "Ewok Elder",
    "ep" => "Emperor Palpatine",
    "fives" => "CT-5555 \"Fives\"",
    "fs" => "Fennec Shand",
    "fotp" => "First Order TIE Pilot",
    "fox" => "First Order Executioner",
    "gas" => "General Skywalker",
    "gat" => "Grand Admiral Thrawn",
    "gba" => "Geonosian Brood Alpha",
    "gg" => "General Grievous",
    "gk" => "General Kenobi",
    "gmt" => "Grand Moff Tarkin",
    "gmy" => "Grand Master Yoda",
    "greef" => "Greef Karga",
    "gso" => "Geonosian Soldier",
    "gsp" => "Geonosian Spy",
    "gv" => "General Veers",
    "han" => "Han Solo",
    "hk" => "HK-47",
    "hoda" => "Hermit Yoda",
    "hs" => "Hera Syndulla",
    "hux" => "General Hux",
    "ig11" => "IG-11",
    "jango" => "Jango Fett",
    "jb" => "Jolee Bindo",
    "je" => "Jyn Erso",
    "jtr" => "Rey (Jedi Training)",
    "jka" => "Jedi Knight Anakin",
    "jkl" => "Jedi Knight Luke Skywalker",
    "jkr" => "Jedi Knight Revan",
    "k2so" => "K-2SO",
    "kj" => "Kanan Jarrus",
    "kr" => "Kylo Ren",
    "kru" => "Kylo Ren (Unmasked)",
    "l337" => "L3-37",
    "mando" => "The Mandalorian",
    "mg" => "Moff Gideon",
    "mj" => "Mara Jade, The Emperor's Hand",
    "mt" => "Mother Talzin",
    "mv" => "Mission Vao",
    "mw" => "Mace Windu",
    "ng" => "Nute Gunray",
    "ni" => "Nightsister Initiate",
    "nz" => "Nightsister Zombie",
    "od" => "Old Daka",
    "padme" => "Padmé Amidala",
    "ptl" => "Poggle the Lesser",
    "qira" => "Qi'ra",
    "ranget" => "Range Trooper",
    "rex" => "CT-7567 \"Rex\"",
    "rs" => "Rey (Scavenger)",
    "set" => "Sith Empire Trooper",
    "sf" => "Sun Fac",
    "sion" => "Darth Sion",
    "so" => "Savage Opress",
    "st" => "Shaak Ti",
    "t&c" => "Threepio & Chewie",
    "tiefp" => "TIE Fighter Pilot",
    "traya" => "Darth Traya",
    "vsc" => "Veteran Smuggler Chewbacca",
    "yhs" => "Young Han Solo",
    "ylc" => "Young Lando Calrissian",
    "wa" => "Wedge Antilles",
    "wt" => "Wat Tambor",
    "zaal" => "Zaalbar",
    "zeb" => "Garazeb \"Zeb\" Orrelios",
    "zw" => "Zam Wesell"
  }


  def expand_acronyms(characters) do
    characters
    |> Enum.map(&{&1, Map.get(@acronyms, String.downcase(&1), &1)})
  end
end
